// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"git.sotatts.online/matrix/matrix/packages/backend/go/obs"
	"git.sotatts.online/matrix/matrix/workflow/api-server/internal/biz"
	"git.sotatts.online/matrix/matrix/workflow/api-server/internal/conf"
	"git.sotatts.online/matrix/matrix/workflow/api-server/internal/data"
	"git.sotatts.online/matrix/matrix/workflow/api-server/internal/server"
	"git.sotatts.online/matrix/matrix/workflow/api-server/internal/service"
	"git.sotatts.online/matrix/matrix/workflow/api-server/pkg/metrics"
	"github.com/go-kratos/kratos/v3"
	"log/slog"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp 初始化 Kratos 应用。
func wireApp(confServer *conf.Server, confData *conf.Data, logger *slog.Logger) (*kratos.App, func(), error) {
	pool, cleanup, err := data.NewDB(confData)
	if err != nil {
		return nil, nil, err
	}
	registry, cleanup2, err := metrics.New(logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	v := metrics.NewTemporalHandler(registry)
	client, cleanup3, err := data.NewTemporalClient(confData, logger, v)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	httpClient := obs.NewHTTPClient()
	dataData := data.NewData(confData, pool, client, httpClient)
	executionStatusRepo := data.NewExecutionStatusRepo(dataData)
	httpclientClient, err := data.NewMaasHTTPClient(confData)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	maasClient := data.NewMaasClient(httpclientClient)
	workerNodeRepo := data.NewWorkerNodeRepo(dataData, maasClient)
	workerUsecase := biz.NewWorkerUsecase(executionStatusRepo, workerNodeRepo)
	workerService := service.NewWorkerService(workerUsecase)
	httpServer := server.NewWorkerHTTPServer(confServer, workerService, logger, registry)
	temporalWorker := server.NewTemporalWorker(confData, client, workerService)
	app := newApp(logger, httpServer, temporalWorker)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
