// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: todo/v1/todo.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationTodoServiceCreateTodo = "/todo.v1.TodoService/CreateTodo"
const OperationTodoServiceDeleteTodo = "/todo.v1.TodoService/DeleteTodo"
const OperationTodoServiceGetTodo = "/todo.v1.TodoService/GetTodo"
const OperationTodoServiceListTodos = "/todo.v1.TodoService/ListTodos"
const OperationTodoServiceSyncTodos = "/todo.v1.TodoService/SyncTodos"
const OperationTodoServiceUpdateTodo = "/todo.v1.TodoService/UpdateTodo"
const OperationTodoServiceWatchTodos = "/todo.v1.TodoService/WatchTodos"

type TodoServiceHTTPServer interface {
	// CreateTodo CreateTodo 创建待办事项，并返回已持久化的记录，
	// 服务端会填充 id、create_time 和 update_time。
	// 请求数据校验失败时返回 INVALID_ARGUMENT。
	CreateTodo(context.Context, *CreateTodoRequest) (*Todo, error)
	// DeleteTodo DeleteTodo 根据 ID 永久删除待办事项。
	// 指定 ID 不存在时返回 NOT_FOUND。
	DeleteTodo(context.Context, *DeleteTodoRequest) (*emptypb.Empty, error)
	// GetTodo GetTodo 根据 ID 返回单个待办事项。
	// 指定 ID 不存在时返回 NOT_FOUND。
	GetTodo(context.Context, *GetTodoRequest) (*Todo, error)
	// ListTodos ListTodos 返回一页待办事项，可选过滤和排序。
	// 使用 TodoSet 中的 next_page_token 获取后续页面。
	// filter、order_by 或 page_token 格式错误时返回 INVALID_ARGUMENT。
	ListTodos(context.Context, *ListTodosRequest) (*TodoSet, error)
	// SyncTodos SyncTodos 打开双向流进行双向同步。
	// 客户端发送描述本地变更的 SyncTodoRequest，
	// 服务端返回反映最终状态的 TodoEvent。
	// 流会持续到任意一方关闭。
	SyncTodos(TodoService_SyncTodosServer) error
	// UpdateTodo UpdateTodo 使用 FieldMask 对已有待办事项执行部分更新。
	// 只有 update_mask 列出的字段会被覆盖，
	// 其他字段保持不变。
	// 目标待办事项不存在时返回 NOT_FOUND，或
	// update_mask 引用了未知字段时返回 INVALID_ARGUMENT。
	UpdateTodo(context.Context, *UpdateTodoRequest) (*Todo, error)
	// WatchTodos WatchTodos 打开服务端流，为每个符合条件的新增、更新或删除发送 TodoEvent。
	// 流会持续到客户端取消或服务端终止。
	WatchTodos(*WatchTodosRequest, TodoService_WatchTodosServer) error
}

func RegisterTodoServiceHTTPServer(s *http.Server, srv TodoServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/v1/todos/create", _TodoService_CreateTodo0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/todos/{id}", _TodoService_GetTodo0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/todos/list", _TodoService_ListTodos0_HTTP_Handler(srv))
	r.Handle("PUT", "/v1/todos/update", _TodoService_UpdateTodo0_HTTP_Handler(srv))
	r.Handle("DELETE", "/v1/todos/{id}", _TodoService_DeleteTodo0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/todos/watch", _TodoService_WatchTodos0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/todos/sync", _TodoService_SyncTodos0_HTTP_Handler(srv))
}

type TodoService_SyncTodosHTTPServer struct {
	http.ServerStream
}

func (x *TodoService_SyncTodosHTTPServer) Send(m *TodoEvent) error {
	return x.ServerStream.Send(m)
}
func (x *TodoService_SyncTodosHTTPServer) Recv() (*SyncTodoRequest, error) {
	m := new(SyncTodoRequest)
	if err := x.ServerStream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

type TodoService_WatchTodosHTTPServer struct {
	http.ServerStream
}

func (x *TodoService_WatchTodosHTTPServer) Send(m *TodoEvent) error {
	return x.ServerStream.Send(m)
}

func _TodoService_CreateTodo0_HTTP_Handler(srv TodoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTodoRequest
		if err := ctx.Bind(&in.Todo); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTodoServiceCreateTodo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTodo(ctx, req.(*CreateTodoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Todo)
		return ctx.Result(200, reply)
	}
}

func _TodoService_GetTodo0_HTTP_Handler(srv TodoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTodoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTodoServiceGetTodo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTodo(ctx, req.(*GetTodoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Todo)
		return ctx.Result(200, reply)
	}
}

func _TodoService_ListTodos0_HTTP_Handler(srv TodoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTodosRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTodoServiceListTodos)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTodos(ctx, req.(*ListTodosRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TodoSet)
		return ctx.Result(200, reply)
	}
}

func _TodoService_UpdateTodo0_HTTP_Handler(srv TodoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTodoRequest
		if err := ctx.Bind(&in.Todo); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTodoServiceUpdateTodo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTodo(ctx, req.(*UpdateTodoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Todo)
		return ctx.Result(200, reply)
	}
}

func _TodoService_DeleteTodo0_HTTP_Handler(srv TodoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTodoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTodoServiceDeleteTodo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTodo(ctx, req.(*DeleteTodoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

func _TodoService_WatchTodos0_HTTP_Handler(srv TodoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WatchTodosRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		stream := http.NewServerSentEventServerStream(ctx)
		http.SetOperation(ctx, OperationTodoServiceWatchTodos)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			stream.SetContext(ctx)
			return nil, srv.WatchTodos(req.(*WatchTodosRequest), &TodoService_WatchTodosHTTPServer{ServerStream: stream})
		})
		_, err := h(ctx, &in)
		return stream.Close(err)
	}
}

func _TodoService_SyncTodos0_HTTP_Handler(srv TodoServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		stream, err := http.NewWebSocketServerStream(ctx)
		if err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTodoServiceSyncTodos)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			stream.SetContext(ctx)
			return nil, srv.SyncTodos(&TodoService_SyncTodosHTTPServer{ServerStream: stream})
		})
		_, err = h(ctx, nil)
		return stream.Close(err)
	}
}

type TodoServiceHTTPClient interface {
	// CreateTodo CreateTodo 创建待办事项，并返回已持久化的记录，
	// 服务端会填充 id、create_time 和 update_time。
	// 请求数据校验失败时返回 INVALID_ARGUMENT。
	CreateTodo(ctx context.Context, req *CreateTodoRequest, opts ...http.CallOption) (rsp *Todo, err error)
	// DeleteTodo DeleteTodo 根据 ID 永久删除待办事项。
	// 指定 ID 不存在时返回 NOT_FOUND。
	DeleteTodo(ctx context.Context, req *DeleteTodoRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetTodo GetTodo 根据 ID 返回单个待办事项。
	// 指定 ID 不存在时返回 NOT_FOUND。
	GetTodo(ctx context.Context, req *GetTodoRequest, opts ...http.CallOption) (rsp *Todo, err error)
	// ListTodos ListTodos 返回一页待办事项，可选过滤和排序。
	// 使用 TodoSet 中的 next_page_token 获取后续页面。
	// filter、order_by 或 page_token 格式错误时返回 INVALID_ARGUMENT。
	ListTodos(ctx context.Context, req *ListTodosRequest, opts ...http.CallOption) (rsp *TodoSet, err error)
	// SyncTodos SyncTodos 打开双向流进行双向同步。
	// 客户端发送描述本地变更的 SyncTodoRequest，
	// 服务端返回反映最终状态的 TodoEvent。
	// 流会持续到任意一方关闭。
	SyncTodos(ctx context.Context, opts ...http.CallOption) (TodoService_SyncTodosClient, error)
	// UpdateTodo UpdateTodo 使用 FieldMask 对已有待办事项执行部分更新。
	// 只有 update_mask 列出的字段会被覆盖，
	// 其他字段保持不变。
	// 目标待办事项不存在时返回 NOT_FOUND，或
	// update_mask 引用了未知字段时返回 INVALID_ARGUMENT。
	UpdateTodo(ctx context.Context, req *UpdateTodoRequest, opts ...http.CallOption) (rsp *Todo, err error)
	// WatchTodos WatchTodos 打开服务端流，为每个符合条件的新增、更新或删除发送 TodoEvent。
	// 流会持续到客户端取消或服务端终止。
	WatchTodos(ctx context.Context, req *WatchTodosRequest, opts ...http.CallOption) (TodoService_WatchTodosClient, error)
}

type TodoServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTodoServiceHTTPClient(client *http.Client) TodoServiceHTTPClient {
	return &TodoServiceHTTPClientImpl{client}
}

type TodoService_SyncTodosHTTPClient struct {
	http.ClientStream
	ctx     context.Context
	cc      *http.Client
	pattern string
	opts    []http.CallOption
}

func (x *TodoService_SyncTodosHTTPClient) open(m *SyncTodoRequest) error {
	if x.ClientStream != nil {
		return nil
	}
	opts := x.opts
	path := http.BuildPath(x.pattern, m)
	stream, err := x.cc.WebSocket(x.ctx, path, opts...)
	if err != nil {
		return err
	}
	x.ClientStream = stream
	return nil
}

func (x *TodoService_SyncTodosHTTPClient) CloseSend() error {
	if err := x.open(nil); err != nil {
		return err
	}
	return x.ClientStream.CloseSend()
}

func (x *TodoService_SyncTodosHTTPClient) Send(m *SyncTodoRequest) error {
	if err := x.open(m); err != nil {
		return err
	}
	return x.ClientStream.Send(m)
}
func (x *TodoService_SyncTodosHTTPClient) Recv() (*TodoEvent, error) {
	if err := x.open(nil); err != nil {
		return nil, err
	}
	m := new(TodoEvent)
	if err := x.ClientStream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

type TodoService_WatchTodosHTTPClient struct {
	http.ClientStream
}

func (x *TodoService_WatchTodosHTTPClient) Recv() (*TodoEvent, error) {
	m := new(TodoEvent)
	if err := x.ClientStream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CreateTodo CreateTodo 创建待办事项，并返回已持久化的记录，
// 服务端会填充 id、create_time 和 update_time。
// 请求数据校验失败时返回 INVALID_ARGUMENT。
func (c *TodoServiceHTTPClientImpl) CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...http.CallOption) (*Todo, error) {
	var out Todo
	pattern := "/v1/todos/create"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("todo"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTodoServiceCreateTodo),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in.Todo, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteTodo DeleteTodo 根据 ID 永久删除待办事项。
// 指定 ID 不存在时返回 NOT_FOUND。
func (c *TodoServiceHTTPClientImpl) DeleteTodo(ctx context.Context, in *DeleteTodoRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/todos/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTodoServiceDeleteTodo),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTodo GetTodo 根据 ID 返回单个待办事项。
// 指定 ID 不存在时返回 NOT_FOUND。
func (c *TodoServiceHTTPClientImpl) GetTodo(ctx context.Context, in *GetTodoRequest, opts ...http.CallOption) (*Todo, error) {
	var out Todo
	pattern := "/v1/todos/{id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTodoServiceGetTodo),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTodos ListTodos 返回一页待办事项，可选过滤和排序。
// 使用 TodoSet 中的 next_page_token 获取后续页面。
// filter、order_by 或 page_token 格式错误时返回 INVALID_ARGUMENT。
func (c *TodoServiceHTTPClientImpl) ListTodos(ctx context.Context, in *ListTodosRequest, opts ...http.CallOption) (*TodoSet, error) {
	var out TodoSet
	pattern := "/v1/todos/list"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationTodoServiceListTodos),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SyncTodos SyncTodos 打开双向流进行双向同步。
// 客户端发送描述本地变更的 SyncTodoRequest，
// 服务端返回反映最终状态的 TodoEvent。
// 流会持续到任意一方关闭。
func (c *TodoServiceHTTPClientImpl) SyncTodos(ctx context.Context, opts ...http.CallOption) (TodoService_SyncTodosClient, error) {
	pattern := "/v1/todos/sync"
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTodoServiceSyncTodos),
		http.PathTemplate(pattern),
	}, opts...)
	return &TodoService_SyncTodosHTTPClient{ctx: ctx, cc: c.cc, pattern: pattern, opts: opts}, nil
}

// UpdateTodo UpdateTodo 使用 FieldMask 对已有待办事项执行部分更新。
// 只有 update_mask 列出的字段会被覆盖，
// 其他字段保持不变。
// 目标待办事项不存在时返回 NOT_FOUND，或
// update_mask 引用了未知字段时返回 INVALID_ARGUMENT。
func (c *TodoServiceHTTPClientImpl) UpdateTodo(ctx context.Context, in *UpdateTodoRequest, opts ...http.CallOption) (*Todo, error) {
	var out Todo
	pattern := "/v1/todos/update"
	path := http.BuildPath(pattern, in, http.WithQueryParams(), http.WithOmitFields("todo"))
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTodoServiceUpdateTodo),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "PUT", path, in.Todo, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// WatchTodos WatchTodos 打开服务端流，为每个符合条件的新增、更新或删除发送 TodoEvent。
// 流会持续到客户端取消或服务端终止。
func (c *TodoServiceHTTPClientImpl) WatchTodos(ctx context.Context, in *WatchTodosRequest, opts ...http.CallOption) (TodoService_WatchTodosClient, error) {
	pattern := "/v1/todos/watch"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("text/event-stream"),
		http.ContentType("application/protojson"),
		http.Operation(OperationTodoServiceWatchTodos),
		http.PathTemplate(pattern),
	}, opts...)
	stream, err := c.cc.ServerSentEvent(ctx, "GET", path, nil, opts...)
	if err != nil {
		return nil, err
	}
	return &TodoService_WatchTodosHTTPClient{ClientStream: stream}, nil
}
