server:
  http:
    addr: 0.0.0.0:8081
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
data:
  temporal:
    addr: 127.0.0.1:17233
    namespace: default
    task_queue: workflow
  maas_api_gateway:
    base_url: http://127.0.0.1:18081
    timeout: 30s
    service_token: ""
