// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: execution.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExecution = `-- name: CreateExecution :one
INSERT INTO execution (
    execution_id,
    uid,
    idempotency_key,
    workflow_id,
    definition,
    status,
    input
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING execution_id, uid, idempotency_key, workflow_id, definition, status, input, output, internal_error_code, internal_error_message, failed_node_id, created_at, started_at, completed_at, updated_at
`

type CreateExecutionParams struct {
	ExecutionID    string
	Uid            int64
	IdempotencyKey pgtype.Text
	WorkflowID     string
	Definition     []byte
	Status         string
	Input          []byte
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, createExecution,
		arg.ExecutionID,
		arg.Uid,
		arg.IdempotencyKey,
		arg.WorkflowID,
		arg.Definition,
		arg.Status,
		arg.Input,
	)
	var i Execution
	err := row.Scan(
		&i.ExecutionID,
		&i.Uid,
		&i.IdempotencyKey,
		&i.WorkflowID,
		&i.Definition,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.InternalErrorCode,
		&i.InternalErrorMessage,
		&i.FailedNodeID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecution = `-- name: GetExecution :one
SELECT execution_id, uid, idempotency_key, workflow_id, definition, status, input, output, internal_error_code, internal_error_message, failed_node_id, created_at, started_at, completed_at, updated_at
FROM execution
WHERE execution_id = $1
`

func (q *Queries) GetExecution(ctx context.Context, executionID string) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecution, executionID)
	var i Execution
	err := row.Scan(
		&i.ExecutionID,
		&i.Uid,
		&i.IdempotencyKey,
		&i.WorkflowID,
		&i.Definition,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.InternalErrorCode,
		&i.InternalErrorMessage,
		&i.FailedNodeID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecutionByIdempotencyKey = `-- name: GetExecutionByIdempotencyKey :one
SELECT execution_id, uid, idempotency_key, workflow_id, definition, status, input, output, internal_error_code, internal_error_message, failed_node_id, created_at, started_at, completed_at, updated_at
FROM execution
WHERE uid = $1
  AND idempotency_key = $2
`

type GetExecutionByIdempotencyKeyParams struct {
	Uid            int64
	IdempotencyKey pgtype.Text
}

func (q *Queries) GetExecutionByIdempotencyKey(ctx context.Context, arg GetExecutionByIdempotencyKeyParams) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecutionByIdempotencyKey, arg.Uid, arg.IdempotencyKey)
	var i Execution
	err := row.Scan(
		&i.ExecutionID,
		&i.Uid,
		&i.IdempotencyKey,
		&i.WorkflowID,
		&i.Definition,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.InternalErrorCode,
		&i.InternalErrorMessage,
		&i.FailedNodeID,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExecutionStatus = `-- name: GetExecutionStatus :one
SELECT status
FROM execution
WHERE execution_id = $1
`

func (q *Queries) GetExecutionStatus(ctx context.Context, executionID string) (string, error) {
	row := q.db.QueryRow(ctx, getExecutionStatus, executionID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listExecutions = `-- name: ListExecutions :many
SELECT execution.execution_id, execution.uid, execution.idempotency_key, execution.workflow_id, execution.definition, execution.status, execution.input, execution.output, execution.internal_error_code, execution.internal_error_message, execution.failed_node_id, execution.created_at, execution.started_at, execution.completed_at, execution.updated_at, workflow.type AS workflow_type
FROM execution
JOIN workflow ON workflow.workflow_id = execution.workflow_id
             AND workflow.uid = execution.uid
WHERE execution.uid = $1
  AND ($2::text = '' OR workflow.type = $2::text)
ORDER BY execution.created_at DESC, execution.execution_id DESC
LIMIT $4
OFFSET $3
`

type ListExecutionsParams struct {
	Uid          int64
	WorkflowType string
	PageOffset   int32
	PageLimit    int32
}

type ListExecutionsRow struct {
	Execution    Execution
	WorkflowType string
}

func (q *Queries) ListExecutions(ctx context.Context, arg ListExecutionsParams) ([]ListExecutionsRow, error) {
	rows, err := q.db.Query(ctx, listExecutions,
		arg.Uid,
		arg.WorkflowType,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExecutionsRow{}
	for rows.Next() {
		var i ListExecutionsRow
		if err := rows.Scan(
			&i.Execution.ExecutionID,
			&i.Execution.Uid,
			&i.Execution.IdempotencyKey,
			&i.Execution.WorkflowID,
			&i.Execution.Definition,
			&i.Execution.Status,
			&i.Execution.Input,
			&i.Execution.Output,
			&i.Execution.InternalErrorCode,
			&i.Execution.InternalErrorMessage,
			&i.Execution.FailedNodeID,
			&i.Execution.CreatedAt,
			&i.Execution.StartedAt,
			&i.Execution.CompletedAt,
			&i.Execution.UpdatedAt,
			&i.WorkflowType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExecutionStatusToRunning = `-- name: UpdateExecutionStatusToRunning :one
UPDATE execution
SET status = 'running',
    started_at = now(),
    updated_at = now()
WHERE execution_id = $1
  AND status = 'pending'
RETURNING execution_id
`

func (q *Queries) UpdateExecutionStatusToRunning(ctx context.Context, executionID string) (string, error) {
	row := q.db.QueryRow(ctx, updateExecutionStatusToRunning, executionID)
	var execution_id string
	err := row.Scan(&execution_id)
	return execution_id, err
}

const updateExecutionStatusToTerminal = `-- name: UpdateExecutionStatusToTerminal :one
UPDATE execution
SET status = $1,
    output = $2,
    internal_error_code = $3,
    internal_error_message = $4,
    failed_node_id = $5,
    completed_at = now(),
    updated_at = now()
WHERE execution_id = $6
  AND status IN ('pending', 'running')
RETURNING execution_id
`

type UpdateExecutionStatusToTerminalParams struct {
	Status               string
	Output               []byte
	InternalErrorCode    pgtype.Int4
	InternalErrorMessage pgtype.Text
	FailedNodeID         pgtype.Text
	ExecutionID          string
}

func (q *Queries) UpdateExecutionStatusToTerminal(ctx context.Context, arg UpdateExecutionStatusToTerminalParams) (string, error) {
	row := q.db.QueryRow(ctx, updateExecutionStatusToTerminal,
		arg.Status,
		arg.Output,
		arg.InternalErrorCode,
		arg.InternalErrorMessage,
		arg.FailedNodeID,
		arg.ExecutionID,
	)
	var execution_id string
	err := row.Scan(&execution_id)
	return execution_id, err
}
