// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Execution struct {
	ExecutionID          string
	Uid                  int64
	IdempotencyKey       pgtype.Text
	WorkflowID           string
	Definition           []byte
	Status               string
	Input                []byte
	Output               []byte
	InternalErrorCode    pgtype.Int4
	InternalErrorMessage pgtype.Text
	FailedNodeID         pgtype.Text
	CreatedAt            pgtype.Timestamptz
	StartedAt            pgtype.Timestamptz
	CompletedAt          pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type Workflow struct {
	WorkflowID string
	Uid        pgtype.Int8
	Name       string
	Type       string
	Definition []byte
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
