// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workflow.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflow (
    workflow_id,
    uid,
    name,
    type,
    definition
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING workflow_id, uid, name, type, definition, created_at, updated_at
`

type CreateWorkflowParams struct {
	WorkflowID string
	Uid        pgtype.Int8
	Name       string
	Type       string
	Definition []byte
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow,
		arg.WorkflowID,
		arg.Uid,
		arg.Name,
		arg.Type,
		arg.Definition,
	)
	var i Workflow
	err := row.Scan(
		&i.WorkflowID,
		&i.Uid,
		&i.Name,
		&i.Type,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :one
DELETE FROM workflow
WHERE workflow_id = $1
RETURNING workflow_id
`

func (q *Queries) DeleteWorkflow(ctx context.Context, workflowID string) (string, error) {
	row := q.db.QueryRow(ctx, deleteWorkflow, workflowID)
	var workflow_id string
	err := row.Scan(&workflow_id)
	return workflow_id, err
}

const getWorkflowByID = `-- name: GetWorkflowByID :one
SELECT workflow_id, uid, name, type, definition, created_at, updated_at
FROM workflow
WHERE workflow_id = $1
`

func (q *Queries) GetWorkflowByID(ctx context.Context, workflowID string) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflowByID, workflowID)
	var i Workflow
	err := row.Scan(
		&i.WorkflowID,
		&i.Uid,
		&i.Name,
		&i.Type,
		&i.Definition,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflowTypesByIDs = `-- name: ListWorkflowTypesByIDs :many
SELECT workflow_id, type
FROM workflow
WHERE workflow_id = ANY($1::varchar[])
`

type ListWorkflowTypesByIDsRow struct {
	WorkflowID string
	Type       string
}

func (q *Queries) ListWorkflowTypesByIDs(ctx context.Context, workflowIds []string) ([]ListWorkflowTypesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowTypesByIDs, workflowIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowTypesByIDsRow{}
	for rows.Next() {
		var i ListWorkflowTypesByIDsRow
		if err := rows.Scan(&i.WorkflowID, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT workflow_id, uid, name, type, definition, created_at, updated_at
FROM workflow
WHERE workflow.uid = $1::bigint
  AND ($2::text = '' OR workflow.type = $2::text)
ORDER BY workflow.created_at DESC, workflow.workflow_id DESC
LIMIT $4
OFFSET $3
`

type ListWorkflowsParams struct {
	Uid        int64
	Type       string
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListWorkflows(ctx context.Context, arg ListWorkflowsParams) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows,
		arg.Uid,
		arg.Type,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workflow{}
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.WorkflowID,
			&i.Uid,
			&i.Name,
			&i.Type,
			&i.Definition,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
