// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workflow/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_WORKFLOW_UNSPECIFIED       ErrorReason = 0
	ErrorReason_EXECUTION_NOT_FOUND        ErrorReason = 1
	ErrorReason_EXECUTION_ALREADY_EXISTS   ErrorReason = 2
	ErrorReason_EXECUTION_INVALID_ARGUMENT ErrorReason = 3
	ErrorReason_EXECUTION_INTERNAL         ErrorReason = 4
	ErrorReason_WORKFLOW_NOT_FOUND         ErrorReason = 5
	ErrorReason_WORKFLOW_INTERNAL          ErrorReason = 6
	ErrorReason_WORKFLOW_INVALID_ARGUMENT  ErrorReason = 7
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "WORKFLOW_UNSPECIFIED",
		1: "EXECUTION_NOT_FOUND",
		2: "EXECUTION_ALREADY_EXISTS",
		3: "EXECUTION_INVALID_ARGUMENT",
		4: "EXECUTION_INTERNAL",
		5: "WORKFLOW_NOT_FOUND",
		6: "WORKFLOW_INTERNAL",
		7: "WORKFLOW_INVALID_ARGUMENT",
	}
	ErrorReason_value = map[string]int32{
		"WORKFLOW_UNSPECIFIED":       0,
		"EXECUTION_NOT_FOUND":        1,
		"EXECUTION_ALREADY_EXISTS":   2,
		"EXECUTION_INVALID_ARGUMENT": 3,
		"EXECUTION_INTERNAL":         4,
		"WORKFLOW_NOT_FOUND":         5,
		"WORKFLOW_INTERNAL":          6,
		"WORKFLOW_INVALID_ARGUMENT":  7,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_workflow_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_workflow_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_workflow_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

var File_workflow_v1_error_reason_proto protoreflect.FileDescriptor

const file_workflow_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1eworkflow/v1/error_reason.proto\x12\vworkflow.v1*\xe4\x01\n" +
	"\vErrorReason\x12\x18\n" +
	"\x14WORKFLOW_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EXECUTION_NOT_FOUND\x10\x01\x12\x1c\n" +
	"\x18EXECUTION_ALREADY_EXISTS\x10\x02\x12\x1e\n" +
	"\x1aEXECUTION_INVALID_ARGUMENT\x10\x03\x12\x16\n" +
	"\x12EXECUTION_INTERNAL\x10\x04\x12\x16\n" +
	"\x12WORKFLOW_NOT_FOUND\x10\x05\x12\x15\n" +
	"\x11WORKFLOW_INTERNAL\x10\x06\x12\x1d\n" +
	"\x19WORKFLOW_INVALID_ARGUMENT\x10\aBIZGgit.sotatts.online/matrix/matrix/workflow/api-server/api/workflow/v1;v1b\x06proto3"

var (
	file_workflow_v1_error_reason_proto_rawDescOnce sync.Once
	file_workflow_v1_error_reason_proto_rawDescData []byte
)

func file_workflow_v1_error_reason_proto_rawDescGZIP() []byte {
	file_workflow_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_workflow_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_v1_error_reason_proto_rawDesc), len(file_workflow_v1_error_reason_proto_rawDesc)))
	})
	return file_workflow_v1_error_reason_proto_rawDescData
}

var file_workflow_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_workflow_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0), // 0: workflow.v1.ErrorReason
}
var file_workflow_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workflow_v1_error_reason_proto_init() }
func file_workflow_v1_error_reason_proto_init() {
	if File_workflow_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_v1_error_reason_proto_rawDesc), len(file_workflow_v1_error_reason_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_workflow_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_workflow_v1_error_reason_proto_enumTypes,
	}.Build()
	File_workflow_v1_error_reason_proto = out.File
	file_workflow_v1_error_reason_proto_goTypes = nil
	file_workflow_v1_error_reason_proto_depIdxs = nil
}
