// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: workflow/v1/workflow.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationWorkflowServiceCreateExecution = "/workflow.v1.WorkflowService/CreateExecution"
const OperationWorkflowServiceCreateWorkflow = "/workflow.v1.WorkflowService/CreateWorkflow"
const OperationWorkflowServiceDeleteWorkflow = "/workflow.v1.WorkflowService/DeleteWorkflow"
const OperationWorkflowServiceGetExecution = "/workflow.v1.WorkflowService/GetExecution"
const OperationWorkflowServiceGetWorkflow = "/workflow.v1.WorkflowService/GetWorkflow"
const OperationWorkflowServiceHealthz = "/workflow.v1.WorkflowService/Healthz"
const OperationWorkflowServiceListExecutions = "/workflow.v1.WorkflowService/ListExecutions"
const OperationWorkflowServiceListNodeTypes = "/workflow.v1.WorkflowService/ListNodeTypes"
const OperationWorkflowServiceListWorkflows = "/workflow.v1.WorkflowService/ListWorkflows"
const OperationWorkflowServiceReadyz = "/workflow.v1.WorkflowService/Readyz"

type WorkflowServiceHTTPServer interface {
	// CreateExecution CreateExecution 发起异步工作流执行。
	CreateExecution(context.Context, *CreateExecutionRequest) (*CreateExecutionResponse, error)
	// CreateWorkflow CreateWorkflow 创建工作流。
	CreateWorkflow(context.Context, *CreateWorkflowRequest) (*CreateWorkflowResponse, error)
	// DeleteWorkflow DeleteWorkflow 删除工作流。
	DeleteWorkflow(context.Context, *DeleteWorkflowRequest) (*emptypb.Empty, error)
	// GetExecution GetExecution 查询工作流执行。
	GetExecution(context.Context, *GetExecutionRequest) (*GetExecutionResponse, error)
	// GetWorkflow GetWorkflow 查询工作流。
	GetWorkflow(context.Context, *GetWorkflowRequest) (*GetWorkflowResponse, error)
	// Healthz Healthz 检查服务进程是否存活。
	Healthz(context.Context, *WorkflowServiceHealthzRequest) (*WorkflowServiceHealthzResponse, error)
	// ListExecutions ListExecutions 查询工作流执行列表。
	ListExecutions(context.Context, *ListExecutionsRequest) (*ListExecutionsResponse, error)
	// ListNodeTypes ListNodeTypes 查询节点类型列表。
	ListNodeTypes(context.Context, *ListNodeTypesRequest) (*ListNodeTypesResponse, error)
	// ListWorkflows ListWorkflows 查询工作流列表。
	ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error)
	// Readyz Readyz 检查服务是否可以接收请求。
	Readyz(context.Context, *WorkflowServiceReadyzRequest) (*WorkflowServiceReadyzResponse, error)
}

func RegisterWorkflowServiceHTTPServer(s *http.Server, srv WorkflowServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/live", _WorkflowService_Healthz0_HTTP_Handler(srv))
	r.Handle("GET", "/ready", _WorkflowService_Readyz0_HTTP_Handler(srv))
	r.Handle("POST", "/internal/v1/executions", _WorkflowService_CreateExecution0_HTTP_Handler(srv))
	r.Handle("GET", "/internal/v1/executions/{execution_id}", _WorkflowService_GetExecution0_HTTP_Handler(srv))
	r.Handle("GET", "/internal/v1/executions", _WorkflowService_ListExecutions0_HTTP_Handler(srv))
	r.Handle("GET", "/internal/v1/node-types", _WorkflowService_ListNodeTypes0_HTTP_Handler(srv))
	r.Handle("POST", "/internal/v1/workflows", _WorkflowService_CreateWorkflow0_HTTP_Handler(srv))
	r.Handle("GET", "/internal/v1/workflows", _WorkflowService_ListWorkflows0_HTTP_Handler(srv))
	r.Handle("GET", "/internal/v1/workflows/{workflow_id}", _WorkflowService_GetWorkflow0_HTTP_Handler(srv))
	r.Handle("DELETE", "/internal/v1/workflows/{workflow_id}", _WorkflowService_DeleteWorkflow0_HTTP_Handler(srv))
}

func _WorkflowService_Healthz0_HTTP_Handler(srv WorkflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WorkflowServiceHealthzRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowServiceHealthz)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Healthz(ctx, req.(*WorkflowServiceHealthzRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WorkflowServiceHealthzResponse)
		return ctx.Result(200, reply)
	}
}

func _WorkflowService_Readyz0_HTTP_Handler(srv WorkflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in WorkflowServiceReadyzRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowServiceReadyz)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Readyz(ctx, req.(*WorkflowServiceReadyzRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*WorkflowServiceReadyzResponse)
		return ctx.Result(200, reply)
	}
}

func _WorkflowService_CreateExecution0_HTTP_Handler(srv WorkflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateExecutionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowServiceCreateExecution)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateExecution(ctx, req.(*CreateExecutionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateExecutionResponse)
		return ctx.Result(200, reply)
	}
}

func _WorkflowService_GetExecution0_HTTP_Handler(srv WorkflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetExecutionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowServiceGetExecution)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetExecution(ctx, req.(*GetExecutionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetExecutionResponse)
		return ctx.Result(200, reply)
	}
}

func _WorkflowService_ListExecutions0_HTTP_Handler(srv WorkflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListExecutionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowServiceListExecutions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListExecutions(ctx, req.(*ListExecutionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListExecutionsResponse)
		return ctx.Result(200, reply)
	}
}

func _WorkflowService_ListNodeTypes0_HTTP_Handler(srv WorkflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListNodeTypesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowServiceListNodeTypes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListNodeTypes(ctx, req.(*ListNodeTypesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListNodeTypesResponse)
		return ctx.Result(200, reply)
	}
}

func _WorkflowService_CreateWorkflow0_HTTP_Handler(srv WorkflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateWorkflowRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowServiceCreateWorkflow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateWorkflow(ctx, req.(*CreateWorkflowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateWorkflowResponse)
		return ctx.Result(200, reply)
	}
}

func _WorkflowService_ListWorkflows0_HTTP_Handler(srv WorkflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListWorkflowsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowServiceListWorkflows)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListWorkflows(ctx, req.(*ListWorkflowsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListWorkflowsResponse)
		return ctx.Result(200, reply)
	}
}

func _WorkflowService_GetWorkflow0_HTTP_Handler(srv WorkflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetWorkflowRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowServiceGetWorkflow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetWorkflow(ctx, req.(*GetWorkflowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetWorkflowResponse)
		return ctx.Result(200, reply)
	}
}

func _WorkflowService_DeleteWorkflow0_HTTP_Handler(srv WorkflowServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteWorkflowRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkflowServiceDeleteWorkflow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteWorkflow(ctx, req.(*DeleteWorkflowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type WorkflowServiceHTTPClient interface {
	// CreateExecution CreateExecution 发起异步工作流执行。
	CreateExecution(ctx context.Context, req *CreateExecutionRequest, opts ...http.CallOption) (rsp *CreateExecutionResponse, err error)
	// CreateWorkflow CreateWorkflow 创建工作流。
	CreateWorkflow(ctx context.Context, req *CreateWorkflowRequest, opts ...http.CallOption) (rsp *CreateWorkflowResponse, err error)
	// DeleteWorkflow DeleteWorkflow 删除工作流。
	DeleteWorkflow(ctx context.Context, req *DeleteWorkflowRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
	// GetExecution GetExecution 查询工作流执行。
	GetExecution(ctx context.Context, req *GetExecutionRequest, opts ...http.CallOption) (rsp *GetExecutionResponse, err error)
	// GetWorkflow GetWorkflow 查询工作流。
	GetWorkflow(ctx context.Context, req *GetWorkflowRequest, opts ...http.CallOption) (rsp *GetWorkflowResponse, err error)
	// Healthz Healthz 检查服务进程是否存活。
	Healthz(ctx context.Context, req *WorkflowServiceHealthzRequest, opts ...http.CallOption) (rsp *WorkflowServiceHealthzResponse, err error)
	// ListExecutions ListExecutions 查询工作流执行列表。
	ListExecutions(ctx context.Context, req *ListExecutionsRequest, opts ...http.CallOption) (rsp *ListExecutionsResponse, err error)
	// ListNodeTypes ListNodeTypes 查询节点类型列表。
	ListNodeTypes(ctx context.Context, req *ListNodeTypesRequest, opts ...http.CallOption) (rsp *ListNodeTypesResponse, err error)
	// ListWorkflows ListWorkflows 查询工作流列表。
	ListWorkflows(ctx context.Context, req *ListWorkflowsRequest, opts ...http.CallOption) (rsp *ListWorkflowsResponse, err error)
	// Readyz Readyz 检查服务是否可以接收请求。
	Readyz(ctx context.Context, req *WorkflowServiceReadyzRequest, opts ...http.CallOption) (rsp *WorkflowServiceReadyzResponse, err error)
}

type WorkflowServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewWorkflowServiceHTTPClient(client *http.Client) WorkflowServiceHTTPClient {
	return &WorkflowServiceHTTPClientImpl{client}
}

// CreateExecution CreateExecution 发起异步工作流执行。
func (c *WorkflowServiceHTTPClientImpl) CreateExecution(ctx context.Context, in *CreateExecutionRequest, opts ...http.CallOption) (*CreateExecutionResponse, error) {
	var out CreateExecutionResponse
	pattern := "/internal/v1/executions"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationWorkflowServiceCreateExecution),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateWorkflow CreateWorkflow 创建工作流。
func (c *WorkflowServiceHTTPClientImpl) CreateWorkflow(ctx context.Context, in *CreateWorkflowRequest, opts ...http.CallOption) (*CreateWorkflowResponse, error) {
	var out CreateWorkflowResponse
	pattern := "/internal/v1/workflows"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationWorkflowServiceCreateWorkflow),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteWorkflow DeleteWorkflow 删除工作流。
func (c *WorkflowServiceHTTPClientImpl) DeleteWorkflow(ctx context.Context, in *DeleteWorkflowRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/internal/v1/workflows/{workflow_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationWorkflowServiceDeleteWorkflow),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetExecution GetExecution 查询工作流执行。
func (c *WorkflowServiceHTTPClientImpl) GetExecution(ctx context.Context, in *GetExecutionRequest, opts ...http.CallOption) (*GetExecutionResponse, error) {
	var out GetExecutionResponse
	pattern := "/internal/v1/executions/{execution_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationWorkflowServiceGetExecution),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetWorkflow GetWorkflow 查询工作流。
func (c *WorkflowServiceHTTPClientImpl) GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...http.CallOption) (*GetWorkflowResponse, error) {
	var out GetWorkflowResponse
	pattern := "/internal/v1/workflows/{workflow_id}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationWorkflowServiceGetWorkflow),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Healthz Healthz 检查服务进程是否存活。
func (c *WorkflowServiceHTTPClientImpl) Healthz(ctx context.Context, in *WorkflowServiceHealthzRequest, opts ...http.CallOption) (*WorkflowServiceHealthzResponse, error) {
	var out WorkflowServiceHealthzResponse
	pattern := "/live"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationWorkflowServiceHealthz),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListExecutions ListExecutions 查询工作流执行列表。
func (c *WorkflowServiceHTTPClientImpl) ListExecutions(ctx context.Context, in *ListExecutionsRequest, opts ...http.CallOption) (*ListExecutionsResponse, error) {
	var out ListExecutionsResponse
	pattern := "/internal/v1/executions"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationWorkflowServiceListExecutions),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListNodeTypes ListNodeTypes 查询节点类型列表。
func (c *WorkflowServiceHTTPClientImpl) ListNodeTypes(ctx context.Context, in *ListNodeTypesRequest, opts ...http.CallOption) (*ListNodeTypesResponse, error) {
	var out ListNodeTypesResponse
	pattern := "/internal/v1/node-types"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationWorkflowServiceListNodeTypes),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListWorkflows ListWorkflows 查询工作流列表。
func (c *WorkflowServiceHTTPClientImpl) ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...http.CallOption) (*ListWorkflowsResponse, error) {
	var out ListWorkflowsResponse
	pattern := "/internal/v1/workflows"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationWorkflowServiceListWorkflows),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Readyz Readyz 检查服务是否可以接收请求。
func (c *WorkflowServiceHTTPClientImpl) Readyz(ctx context.Context, in *WorkflowServiceReadyzRequest, opts ...http.CallOption) (*WorkflowServiceReadyzResponse, error) {
	var out WorkflowServiceReadyzResponse
	pattern := "/ready"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationWorkflowServiceReadyz),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
