// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workflow/v1/workflow.proto

package v1

import (
	_ "github.com/google/gnostic/openapiv3"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowServiceHealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowServiceHealthzRequest) Reset() {
	*x = WorkflowServiceHealthzRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowServiceHealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowServiceHealthzRequest) ProtoMessage() {}

func (x *WorkflowServiceHealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowServiceHealthzRequest.ProtoReflect.Descriptor instead.
func (*WorkflowServiceHealthzRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{0}
}

type WorkflowServiceHealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowServiceHealthzResponse) Reset() {
	*x = WorkflowServiceHealthzResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowServiceHealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowServiceHealthzResponse) ProtoMessage() {}

func (x *WorkflowServiceHealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowServiceHealthzResponse.ProtoReflect.Descriptor instead.
func (*WorkflowServiceHealthzResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{1}
}

type WorkflowServiceReadyzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowServiceReadyzRequest) Reset() {
	*x = WorkflowServiceReadyzRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowServiceReadyzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowServiceReadyzRequest) ProtoMessage() {}

func (x *WorkflowServiceReadyzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowServiceReadyzRequest.ProtoReflect.Descriptor instead.
func (*WorkflowServiceReadyzRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{2}
}

type WorkflowServiceReadyzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowServiceReadyzResponse) Reset() {
	*x = WorkflowServiceReadyzResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowServiceReadyzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowServiceReadyzResponse) ProtoMessage() {}

func (x *WorkflowServiceReadyzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowServiceReadyzResponse.ProtoReflect.Descriptor instead.
func (*WorkflowServiceReadyzResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{3}
}

type CreateExecutionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uid            int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,proto3" json:"idempotency_key,omitempty"`
	WorkflowId     string                 `protobuf:"bytes,3,opt,name=workflow_id,proto3" json:"workflow_id,omitempty"`
	Input          *structpb.Struct       `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateExecutionRequest) Reset() {
	*x = CreateExecutionRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExecutionRequest) ProtoMessage() {}

func (x *CreateExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExecutionRequest.ProtoReflect.Descriptor instead.
func (*CreateExecutionRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *CreateExecutionRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateExecutionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateExecutionRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *CreateExecutionRequest) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

type CreateExecutionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode         int32                  `protobuf:"varint,1,opt,name=error_code,proto3" json:"error_code,omitempty"`
	ErrorMsg          string                 `protobuf:"bytes,2,opt,name=error_msg,proto3" json:"error_msg,omitempty"`
	InternalErrorCode int32                  `protobuf:"varint,3,opt,name=internal_error_code,proto3" json:"internal_error_code,omitempty"`
	InternalErrorMsg  string                 `protobuf:"bytes,4,opt,name=internal_error_msg,proto3" json:"internal_error_msg,omitempty"`
	Data              *CreateExecutionData   `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateExecutionResponse) Reset() {
	*x = CreateExecutionResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExecutionResponse) ProtoMessage() {}

func (x *CreateExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExecutionResponse.ProtoReflect.Descriptor instead.
func (*CreateExecutionResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *CreateExecutionResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CreateExecutionResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *CreateExecutionResponse) GetInternalErrorCode() int32 {
	if x != nil {
		return x.InternalErrorCode
	}
	return 0
}

func (x *CreateExecutionResponse) GetInternalErrorMsg() string {
	if x != nil {
		return x.InternalErrorMsg
	}
	return ""
}

func (x *CreateExecutionResponse) GetData() *CreateExecutionData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateExecutionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExecutionData) Reset() {
	*x = CreateExecutionData{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExecutionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExecutionData) ProtoMessage() {}

func (x *CreateExecutionData) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExecutionData.ProtoReflect.Descriptor instead.
func (*CreateExecutionData) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *CreateExecutionData) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExecutionRequest) Reset() {
	*x = GetExecutionRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionRequest) ProtoMessage() {}

func (x *GetExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionRequest.ProtoReflect.Descriptor instead.
func (*GetExecutionRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *GetExecutionRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetExecutionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode         int32                  `protobuf:"varint,1,opt,name=error_code,proto3" json:"error_code,omitempty"`
	ErrorMsg          string                 `protobuf:"bytes,2,opt,name=error_msg,proto3" json:"error_msg,omitempty"`
	InternalErrorCode int32                  `protobuf:"varint,3,opt,name=internal_error_code,proto3" json:"internal_error_code,omitempty"`
	InternalErrorMsg  string                 `protobuf:"bytes,4,opt,name=internal_error_msg,proto3" json:"internal_error_msg,omitempty"`
	Data              *Execution             `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetExecutionResponse) Reset() {
	*x = GetExecutionResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExecutionResponse) ProtoMessage() {}

func (x *GetExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExecutionResponse.ProtoReflect.Descriptor instead.
func (*GetExecutionResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *GetExecutionResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GetExecutionResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *GetExecutionResponse) GetInternalErrorCode() int32 {
	if x != nil {
		return x.InternalErrorCode
	}
	return 0
}

func (x *GetExecutionResponse) GetInternalErrorMsg() string {
	if x != nil {
		return x.InternalErrorMsg
	}
	return ""
}

func (x *GetExecutionResponse) GetData() *Execution {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListExecutionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	WorkflowType  string                 `protobuf:"bytes,2,opt,name=workflow_type,proto3" json:"workflow_type,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExecutionsRequest) Reset() {
	*x = ListExecutionsRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsRequest) ProtoMessage() {}

func (x *ListExecutionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsRequest.ProtoReflect.Descriptor instead.
func (*ListExecutionsRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *ListExecutionsRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ListExecutionsRequest) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *ListExecutionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListExecutionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListExecutionsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode         int32                  `protobuf:"varint,1,opt,name=error_code,proto3" json:"error_code,omitempty"`
	ErrorMsg          string                 `protobuf:"bytes,2,opt,name=error_msg,proto3" json:"error_msg,omitempty"`
	InternalErrorCode int32                  `protobuf:"varint,3,opt,name=internal_error_code,proto3" json:"internal_error_code,omitempty"`
	InternalErrorMsg  string                 `protobuf:"bytes,4,opt,name=internal_error_msg,proto3" json:"internal_error_msg,omitempty"`
	Data              *ExecutionPage         `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListExecutionsResponse) Reset() {
	*x = ListExecutionsResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExecutionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExecutionsResponse) ProtoMessage() {}

func (x *ListExecutionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExecutionsResponse.ProtoReflect.Descriptor instead.
func (*ListExecutionsResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *ListExecutionsResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ListExecutionsResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ListExecutionsResponse) GetInternalErrorCode() int32 {
	if x != nil {
		return x.InternalErrorCode
	}
	return 0
}

func (x *ListExecutionsResponse) GetInternalErrorMsg() string {
	if x != nil {
		return x.InternalErrorMsg
	}
	return ""
}

func (x *ListExecutionsResponse) GetData() *ExecutionPage {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecutionPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Executions    []*Execution           `protobuf:"bytes,4,rep,name=executions,proto3" json:"executions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionPage) Reset() {
	*x = ExecutionPage{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionPage) ProtoMessage() {}

func (x *ExecutionPage) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionPage.ProtoReflect.Descriptor instead.
func (*ExecutionPage) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *ExecutionPage) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ExecutionPage) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ExecutionPage) GetExecutions() []*Execution {
	if x != nil {
		return x.Executions
	}
	return nil
}

// Execution 表示一次工作流执行。
type Execution struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId    string                 `protobuf:"bytes,1,opt,name=execution_id,proto3" json:"execution_id,omitempty"`
	Uid            int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,proto3" json:"idempotency_key,omitempty"`
	WorkflowId     string                 `protobuf:"bytes,4,opt,name=workflow_id,proto3" json:"workflow_id,omitempty"`
	WorkflowType   string                 `protobuf:"bytes,5,opt,name=workflow_type,proto3" json:"workflow_type,omitempty"`
	// Status 表示执行状态。
	Status               string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Input                *structpb.Struct       `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`
	Output               *structpb.Value        `protobuf:"bytes,8,opt,name=output,proto3" json:"output,omitempty"`
	InternalErrorCode    int32                  `protobuf:"varint,9,opt,name=internal_error_code,proto3" json:"internal_error_code,omitempty"`
	InternalErrorMessage string                 `protobuf:"bytes,10,opt,name=internal_error_message,proto3" json:"internal_error_message,omitempty"`
	FailedNodeId         string                 `protobuf:"bytes,11,opt,name=failed_node_id,proto3" json:"failed_node_id,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,proto3" json:"created_at,omitempty"`
	StartedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=started_at,proto3" json:"started_at,omitempty"`
	CompletedAt          *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=completed_at,proto3" json:"completed_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Execution) Reset() {
	*x = Execution{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Execution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Execution) ProtoMessage() {}

func (x *Execution) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Execution.ProtoReflect.Descriptor instead.
func (*Execution) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *Execution) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *Execution) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Execution) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Execution) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Execution) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *Execution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Execution) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Execution) GetOutput() *structpb.Value {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *Execution) GetInternalErrorCode() int32 {
	if x != nil {
		return x.InternalErrorCode
	}
	return 0
}

func (x *Execution) GetInternalErrorMessage() string {
	if x != nil {
		return x.InternalErrorMessage
	}
	return ""
}

func (x *Execution) GetFailedNodeId() string {
	if x != nil {
		return x.FailedNodeId
	}
	return ""
}

func (x *Execution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Execution) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Execution) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Execution) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ListNodeTypesRequest 是查询节点类型列表的请求。
type ListNodeTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodeTypesRequest) Reset() {
	*x = ListNodeTypesRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodeTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodeTypesRequest) ProtoMessage() {}

func (x *ListNodeTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodeTypesRequest.ProtoReflect.Descriptor instead.
func (*ListNodeTypesRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{13}
}

// ListNodeTypesResponse 是查询节点类型列表的响应。
type ListNodeTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeTypes     []*NodeType            `protobuf:"bytes,1,rep,name=node_types,proto3" json:"node_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodeTypesResponse) Reset() {
	*x = ListNodeTypesResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodeTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodeTypesResponse) ProtoMessage() {}

func (x *ListNodeTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodeTypesResponse.ProtoReflect.Descriptor instead.
func (*ListNodeTypesResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{14}
}

func (x *ListNodeTypesResponse) GetNodeTypes() []*NodeType {
	if x != nil {
		return x.NodeTypes
	}
	return nil
}

// NodeType 表示节点类型及其输入输出。
type NodeType struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Type          string                       `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Inputs        map[string]*InputDefinition  `protobuf:"bytes,2,rep,name=inputs,proto3" json:"inputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Outputs       map[string]*OutputDefinition `protobuf:"bytes,3,rep,name=outputs,proto3" json:"outputs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeType) Reset() {
	*x = NodeType{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeType) ProtoMessage() {}

func (x *NodeType) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeType.ProtoReflect.Descriptor instead.
func (*NodeType) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{15}
}

func (x *NodeType) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NodeType) GetInputs() map[string]*InputDefinition {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *NodeType) GetOutputs() map[string]*OutputDefinition {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type InputDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type 表示输入值类型。
	Type          string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Required      bool   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputDefinition) Reset() {
	*x = InputDefinition{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputDefinition) ProtoMessage() {}

func (x *InputDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputDefinition.ProtoReflect.Descriptor instead.
func (*InputDefinition) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{16}
}

func (x *InputDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InputDefinition) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type OutputDefinition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type 表示输出值类型。
	Type          string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputDefinition) Reset() {
	*x = OutputDefinition{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputDefinition) ProtoMessage() {}

func (x *OutputDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputDefinition.ProtoReflect.Descriptor instead.
func (*OutputDefinition) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{17}
}

func (x *OutputDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateWorkflowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UID 标识工作流所属用户。
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Name 是工作流的展示名称。
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Type 标识工作流类型，例如 template 或 AI 工作流。
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// Definition 是需要保存的工作流图定义。
	Definition    *Definition `protobuf:"bytes,4,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowRequest) Reset() {
	*x = CreateWorkflowRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowRequest) ProtoMessage() {}

func (x *CreateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{18}
}

func (x *CreateWorkflowRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *CreateWorkflowRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWorkflowRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateWorkflowRequest) GetDefinition() *Definition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type CreateWorkflowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ErrorCode 是对外错误码。
	ErrorCode int32 `protobuf:"varint,1,opt,name=error_code,proto3" json:"error_code,omitempty"`
	// ErrorMsg 是对外错误信息。
	ErrorMsg string `protobuf:"bytes,2,opt,name=error_msg,proto3" json:"error_msg,omitempty"`
	// InternalErrorCode 是内部错误码。
	InternalErrorCode int32 `protobuf:"varint,3,opt,name=internal_error_code,proto3" json:"internal_error_code,omitempty"`
	// InternalErrorMsg 是内部错误信息。
	InternalErrorMsg string `protobuf:"bytes,4,opt,name=internal_error_msg,proto3" json:"internal_error_msg,omitempty"`
	// Data 是创建后的工作流。
	Data          *Workflow `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWorkflowResponse) Reset() {
	*x = CreateWorkflowResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkflowResponse) ProtoMessage() {}

func (x *CreateWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{19}
}

func (x *CreateWorkflowResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *CreateWorkflowResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *CreateWorkflowResponse) GetInternalErrorCode() int32 {
	if x != nil {
		return x.InternalErrorCode
	}
	return 0
}

func (x *CreateWorkflowResponse) GetInternalErrorMsg() string {
	if x != nil {
		return x.InternalErrorMsg
	}
	return ""
}

func (x *CreateWorkflowResponse) GetData() *Workflow {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{20}
}

func (x *ListWorkflowsRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ListWorkflowsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListWorkflowsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWorkflowsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListWorkflowsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode         int32                  `protobuf:"varint,1,opt,name=error_code,proto3" json:"error_code,omitempty"`
	ErrorMsg          string                 `protobuf:"bytes,2,opt,name=error_msg,proto3" json:"error_msg,omitempty"`
	InternalErrorCode int32                  `protobuf:"varint,3,opt,name=internal_error_code,proto3" json:"internal_error_code,omitempty"`
	InternalErrorMsg  string                 `protobuf:"bytes,4,opt,name=internal_error_msg,proto3" json:"internal_error_msg,omitempty"`
	Data              *WorkflowPage          `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{21}
}

func (x *ListWorkflowsResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *ListWorkflowsResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ListWorkflowsResponse) GetInternalErrorCode() int32 {
	if x != nil {
		return x.InternalErrorCode
	}
	return 0
}

func (x *ListWorkflowsResponse) GetInternalErrorMsg() string {
	if x != nil {
		return x.InternalErrorMsg
	}
	return ""
}

func (x *ListWorkflowsResponse) GetData() *WorkflowPage {
	if x != nil {
		return x.Data
	}
	return nil
}

type WorkflowPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Workflows     []*Workflow            `protobuf:"bytes,4,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowPage) Reset() {
	*x = WorkflowPage{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowPage) ProtoMessage() {}

func (x *WorkflowPage) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowPage.ProtoReflect.Descriptor instead.
func (*WorkflowPage) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{22}
}

func (x *WorkflowPage) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *WorkflowPage) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WorkflowPage) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

// GetWorkflowRequest 是查询工作流的请求。
type GetWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowRequest) Reset() {
	*x = GetWorkflowRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowRequest) ProtoMessage() {}

func (x *GetWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{23}
}

func (x *GetWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type GetWorkflowResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode         int32                  `protobuf:"varint,1,opt,name=error_code,proto3" json:"error_code,omitempty"`
	ErrorMsg          string                 `protobuf:"bytes,2,opt,name=error_msg,proto3" json:"error_msg,omitempty"`
	InternalErrorCode int32                  `protobuf:"varint,3,opt,name=internal_error_code,proto3" json:"internal_error_code,omitempty"`
	InternalErrorMsg  string                 `protobuf:"bytes,4,opt,name=internal_error_msg,proto3" json:"internal_error_msg,omitempty"`
	Data              *Workflow              `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetWorkflowResponse) Reset() {
	*x = GetWorkflowResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowResponse) ProtoMessage() {}

func (x *GetWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{24}
}

func (x *GetWorkflowResponse) GetErrorCode() int32 {
	if x != nil {
		return x.ErrorCode
	}
	return 0
}

func (x *GetWorkflowResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *GetWorkflowResponse) GetInternalErrorCode() int32 {
	if x != nil {
		return x.InternalErrorCode
	}
	return 0
}

func (x *GetWorkflowResponse) GetInternalErrorMsg() string {
	if x != nil {
		return x.InternalErrorMsg
	}
	return ""
}

func (x *GetWorkflowResponse) GetData() *Workflow {
	if x != nil {
		return x.Data
	}
	return nil
}

// Workflow 表示工作流定义。
type Workflow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WorkflowID 是工作流的稳定标识。
	WorkflowId string `protobuf:"bytes,1,opt,name=workflow_id,proto3" json:"workflow_id,omitempty"`
	// UID 标识工作流所属用户。
	Uid int64 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	// Name 是工作流的展示名称。
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Type 标识工作流类型。
	Type string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	// Definition 是当前工作流图定义。
	Definition *Definition `protobuf:"bytes,5,opt,name=definition,proto3" json:"definition,omitempty"`
	// CreatedAt 是工作流的创建时间。
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,proto3" json:"created_at,omitempty"`
	// UpdatedAt 是工作流的更新时间。
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{25}
}

func (x *Workflow) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Workflow) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Workflow) GetDefinition() *Definition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *Workflow) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Workflow) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Definition 表示工作流的图定义。
type Definition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Nodes 保存图中的节点定义。
	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	// Edges 保存节点之间的连线定义。
	Edges         []*Edge `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Definition) Reset() {
	*x = Definition{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Definition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Definition) ProtoMessage() {}

func (x *Definition) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Definition.ProtoReflect.Descriptor instead.
func (*Definition) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{26}
}

func (x *Definition) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Definition) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type Node struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID 在当前 Definition 内唯一，并供 Edge 引用。
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Type 标识节点的执行类型。
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Preset 保存节点定义中预先配置的数据。
	Preset        map[string]*structpb.Value `protobuf:"bytes,3,rep,name=preset,proto3" json:"preset,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{27}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Node) GetPreset() map[string]*structpb.Value {
	if x != nil {
		return x.Preset
	}
	return nil
}

// Edge 表示节点之间的数据依赖或控制流分支。
type Edge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FromNode 是连线起点的节点 ID。
	FromNode string `protobuf:"bytes,1,opt,name=from_node,proto3" json:"from_node,omitempty"`
	// FromBranch 是 Router 分支 ID，非 Router 出边为空。
	FromBranch string `protobuf:"bytes,2,opt,name=from_branch,proto3" json:"from_branch,omitempty"`
	// FromPort 标识源数据字段。
	FromPort string `protobuf:"bytes,3,opt,name=from_port,proto3" json:"from_port,omitempty"`
	// ToNode 是连线终点的节点 ID。
	ToNode string `protobuf:"bytes,4,opt,name=to_node,proto3" json:"to_node,omitempty"`
	// ToInput 标识目标节点接收数据的输入字段，控制流中留空。
	ToInput       string `protobuf:"bytes,5,opt,name=to_input,proto3" json:"to_input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{28}
}

func (x *Edge) GetFromNode() string {
	if x != nil {
		return x.FromNode
	}
	return ""
}

func (x *Edge) GetFromBranch() string {
	if x != nil {
		return x.FromBranch
	}
	return ""
}

func (x *Edge) GetFromPort() string {
	if x != nil {
		return x.FromPort
	}
	return ""
}

func (x *Edge) GetToNode() string {
	if x != nil {
		return x.ToNode
	}
	return ""
}

func (x *Edge) GetToInput() string {
	if x != nil {
		return x.ToInput
	}
	return ""
}

var File_workflow_v1_workflow_proto protoreflect.FileDescriptor

const file_workflow_v1_workflow_proto_rawDesc = "" +
	"\n" +
	"\x1aworkflow/v1/workflow.proto\x12\vworkflow.v1\x1a$gnostic/openapi/v3/annotations.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x1f\n" +
	"\x1dWorkflowServiceHealthzRequest\" \n" +
	"\x1eWorkflowServiceHealthzResponse\"\x1e\n" +
	"\x1cWorkflowServiceReadyzRequest\"\x1f\n" +
	"\x1dWorkflowServiceReadyzResponse\"\xc9\x01\n" +
	"\x16CreateExecutionRequest\x12*\n" +
	"\x03uid\x18\x01 \x01(\x03B\x18\xe0A\x02\xbaG\x12\xca\x01\ainteger\x9a\x02\x05int64R\x03uid\x12-\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tB\x03\xe0A\x02R\x0fidempotency_key\x12%\n" +
	"\vworkflow_id\x18\x03 \x01(\tB\x03\xe0A\x02R\vworkflow_id\x12-\n" +
	"\x05input\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x05input\"\xef\x01\n" +
	"\x17CreateExecutionResponse\x12\x1e\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\n" +
	"error_code\x12\x1c\n" +
	"\terror_msg\x18\x02 \x01(\tR\terror_msg\x120\n" +
	"\x13internal_error_code\x18\x03 \x01(\x05R\x13internal_error_code\x12.\n" +
	"\x12internal_error_msg\x18\x04 \x01(\tR\x12internal_error_msg\x124\n" +
	"\x04data\x18\x05 \x01(\v2 .workflow.v1.CreateExecutionDataR\x04data\"9\n" +
	"\x13CreateExecutionData\x12\"\n" +
	"\fexecution_id\x18\x01 \x01(\tR\fexecution_id\"9\n" +
	"\x13GetExecutionRequest\x12\"\n" +
	"\fexecution_id\x18\x01 \x01(\tR\fexecution_id\"\xe2\x01\n" +
	"\x14GetExecutionResponse\x12\x1e\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\n" +
	"error_code\x12\x1c\n" +
	"\terror_msg\x18\x02 \x01(\tR\terror_msg\x120\n" +
	"\x13internal_error_code\x18\x03 \x01(\x05R\x13internal_error_code\x12.\n" +
	"\x12internal_error_msg\x18\x04 \x01(\tR\x12internal_error_msg\x12*\n" +
	"\x04data\x18\x05 \x01(\v2\x16.workflow.v1.ExecutionR\x04data\"\x94\x01\n" +
	"\x15ListExecutionsRequest\x12'\n" +
	"\x03uid\x18\x01 \x01(\x03B\x15\xbaG\x12\xca\x01\ainteger\x9a\x02\x05int64R\x03uid\x12$\n" +
	"\rworkflow_type\x18\x02 \x01(\tR\rworkflow_type\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xe8\x01\n" +
	"\x16ListExecutionsResponse\x12\x1e\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\n" +
	"error_code\x12\x1c\n" +
	"\terror_msg\x18\x02 \x01(\tR\terror_msg\x120\n" +
	"\x13internal_error_code\x18\x03 \x01(\x05R\x13internal_error_code\x12.\n" +
	"\x12internal_error_msg\x18\x04 \x01(\tR\x12internal_error_msg\x12.\n" +
	"\x04data\x18\x05 \x01(\v2\x1a.workflow.v1.ExecutionPageR\x04data\"u\n" +
	"\rExecutionPage\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x126\n" +
	"\n" +
	"executions\x18\x04 \x03(\v2\x16.workflow.v1.ExecutionR\n" +
	"executions\"\xc7\x05\n" +
	"\tExecution\x12\"\n" +
	"\fexecution_id\x18\x01 \x01(\tR\fexecution_id\x12'\n" +
	"\x03uid\x18\x02 \x01(\x03B\x15\xbaG\x12\xca\x01\ainteger\x9a\x02\x05int64R\x03uid\x12(\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0fidempotency_key\x12 \n" +
	"\vworkflow_id\x18\x04 \x01(\tR\vworkflow_id\x12$\n" +
	"\rworkflow_type\x18\x05 \x01(\tR\rworkflow_type\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12-\n" +
	"\x05input\x18\a \x01(\v2\x17.google.protobuf.StructR\x05input\x12.\n" +
	"\x06output\x18\b \x01(\v2\x16.google.protobuf.ValueR\x06output\x120\n" +
	"\x13internal_error_code\x18\t \x01(\x05R\x13internal_error_code\x126\n" +
	"\x16internal_error_message\x18\n" +
	" \x01(\tR\x16internal_error_message\x12&\n" +
	"\x0efailed_node_id\x18\v \x01(\tR\x0efailed_node_id\x12:\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x12:\n" +
	"\n" +
	"started_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"started_at\x12>\n" +
	"\fcompleted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\fcompleted_at\x12:\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_at\"\x16\n" +
	"\x14ListNodeTypesRequest\"N\n" +
	"\x15ListNodeTypesResponse\x125\n" +
	"\n" +
	"node_types\x18\x01 \x03(\v2\x15.workflow.v1.NodeTypeR\n" +
	"node_types\"\xcb\x02\n" +
	"\bNodeType\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x129\n" +
	"\x06inputs\x18\x02 \x03(\v2!.workflow.v1.NodeType.InputsEntryR\x06inputs\x12<\n" +
	"\aoutputs\x18\x03 \x03(\v2\".workflow.v1.NodeType.OutputsEntryR\aoutputs\x1aW\n" +
	"\vInputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.workflow.v1.InputDefinitionR\x05value:\x028\x01\x1aY\n" +
	"\fOutputsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.workflow.v1.OutputDefinitionR\x05value:\x028\x01\"A\n" +
	"\x0fInputDefinition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\"&\n" +
	"\x10OutputDefinition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"\xa1\x01\n" +
	"\x15CreateWorkflowRequest\x12'\n" +
	"\x03uid\x18\x01 \x01(\x03B\x15\xbaG\x12\xca\x01\ainteger\x9a\x02\x05int64R\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x127\n" +
	"\n" +
	"definition\x18\x04 \x01(\v2\x17.workflow.v1.DefinitionR\n" +
	"definition\"\xe3\x01\n" +
	"\x16CreateWorkflowResponse\x12\x1e\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\n" +
	"error_code\x12\x1c\n" +
	"\terror_msg\x18\x02 \x01(\tR\terror_msg\x120\n" +
	"\x13internal_error_code\x18\x03 \x01(\x05R\x13internal_error_code\x12.\n" +
	"\x12internal_error_msg\x18\x04 \x01(\tR\x12internal_error_msg\x12)\n" +
	"\x04data\x18\x05 \x01(\v2\x15.workflow.v1.WorkflowR\x04data\"\x81\x01\n" +
	"\x14ListWorkflowsRequest\x12'\n" +
	"\x03uid\x18\x01 \x01(\x03B\x15\xbaG\x12\xca\x01\ainteger\x9a\x02\x05int64R\x03uid\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xe6\x01\n" +
	"\x15ListWorkflowsResponse\x12\x1e\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\n" +
	"error_code\x12\x1c\n" +
	"\terror_msg\x18\x02 \x01(\tR\terror_msg\x120\n" +
	"\x13internal_error_code\x18\x03 \x01(\x05R\x13internal_error_code\x12.\n" +
	"\x12internal_error_msg\x18\x04 \x01(\tR\x12internal_error_msg\x12-\n" +
	"\x04data\x18\x05 \x01(\v2\x19.workflow.v1.WorkflowPageR\x04data\"q\n" +
	"\fWorkflowPage\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x123\n" +
	"\tworkflows\x18\x04 \x03(\v2\x15.workflow.v1.WorkflowR\tworkflows\"6\n" +
	"\x12GetWorkflowRequest\x12 \n" +
	"\vworkflow_id\x18\x01 \x01(\tR\vworkflow_id\"\xe0\x01\n" +
	"\x13GetWorkflowResponse\x12\x1e\n" +
	"\n" +
	"error_code\x18\x01 \x01(\x05R\n" +
	"error_code\x12\x1c\n" +
	"\terror_msg\x18\x02 \x01(\tR\terror_msg\x120\n" +
	"\x13internal_error_code\x18\x03 \x01(\x05R\x13internal_error_code\x12.\n" +
	"\x12internal_error_msg\x18\x04 \x01(\tR\x12internal_error_msg\x12)\n" +
	"\x04data\x18\x05 \x01(\v2\x15.workflow.v1.WorkflowR\x04data\"\xae\x02\n" +
	"\bWorkflow\x12 \n" +
	"\vworkflow_id\x18\x01 \x01(\tR\vworkflow_id\x12'\n" +
	"\x03uid\x18\x02 \x01(\x03B\x15\xbaG\x12\xca\x01\ainteger\x9a\x02\x05int64R\x03uid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x127\n" +
	"\n" +
	"definition\x18\x05 \x01(\v2\x17.workflow.v1.DefinitionR\n" +
	"definition\x12:\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x12:\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_at\"^\n" +
	"\n" +
	"Definition\x12'\n" +
	"\x05nodes\x18\x01 \x03(\v2\x11.workflow.v1.NodeR\x05nodes\x12'\n" +
	"\x05edges\x18\x02 \x03(\v2\x11.workflow.v1.EdgeR\x05edges\"\xb4\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x125\n" +
	"\x06preset\x18\x03 \x03(\v2\x1d.workflow.v1.Node.PresetEntryR\x06preset\x1aQ\n" +
	"\vPresetEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\x9a\x01\n" +
	"\x04Edge\x12\x1c\n" +
	"\tfrom_node\x18\x01 \x01(\tR\tfrom_node\x12 \n" +
	"\vfrom_branch\x18\x02 \x01(\tR\vfrom_branch\x12\x1c\n" +
	"\tfrom_port\x18\x03 \x01(\tR\tfrom_port\x12\x18\n" +
	"\ato_node\x18\x04 \x01(\tR\ato_node\x12\x1a\n" +
	"\bto_input\x18\x05 \x01(\tR\bto_input2\xe9\b\n" +
	"\x0fWorkflowService\x12q\n" +
	"\aHealthz\x12*.workflow.v1.WorkflowServiceHealthzRequest\x1a+.workflow.v1.WorkflowServiceHealthzResponse\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/live\x12o\n" +
	"\x06Readyz\x12).workflow.v1.WorkflowServiceReadyzRequest\x1a*.workflow.v1.WorkflowServiceReadyzResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/ready\x12\x80\x01\n" +
	"\x0fCreateExecution\x12#.workflow.v1.CreateExecutionRequest\x1a$.workflow.v1.CreateExecutionResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/internal/v1/executions\x12\x83\x01\n" +
	"\fGetExecution\x12 .workflow.v1.GetExecutionRequest\x1a!.workflow.v1.GetExecutionResponse\".\x82\xd3\xe4\x93\x02(\x12&/internal/v1/executions/{execution_id}\x12z\n" +
	"\x0eListExecutions\x12\".workflow.v1.ListExecutionsRequest\x1a#.workflow.v1.ListExecutionsResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/internal/v1/executions\x12w\n" +
	"\rListNodeTypes\x12!.workflow.v1.ListNodeTypesRequest\x1a\".workflow.v1.ListNodeTypesResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/internal/v1/node-types\x12|\n" +
	"\x0eCreateWorkflow\x12\".workflow.v1.CreateWorkflowRequest\x1a#.workflow.v1.CreateWorkflowResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/internal/v1/workflows\x12v\n" +
	"\rListWorkflows\x12!.workflow.v1.ListWorkflowsRequest\x1a\".workflow.v1.ListWorkflowsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/internal/v1/workflows\x12~\n" +
	"\vGetWorkflow\x12\x1f.workflow.v1.GetWorkflowRequest\x1a .workflow.v1.GetWorkflowResponse\",\x82\xd3\xe4\x93\x02&\x12$/internal/v1/workflows/{workflow_id}BIZGgit.sotatts.online/matrix/matrix/workflow/api-server/api/workflow/v1;v1b\x06proto3"

var (
	file_workflow_v1_workflow_proto_rawDescOnce sync.Once
	file_workflow_v1_workflow_proto_rawDescData []byte
)

func file_workflow_v1_workflow_proto_rawDescGZIP() []byte {
	file_workflow_v1_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_v1_workflow_proto_rawDesc), len(file_workflow_v1_workflow_proto_rawDesc)))
	})
	return file_workflow_v1_workflow_proto_rawDescData
}

var file_workflow_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_workflow_v1_workflow_proto_goTypes = []any{
	(*WorkflowServiceHealthzRequest)(nil),  // 0: workflow.v1.WorkflowServiceHealthzRequest
	(*WorkflowServiceHealthzResponse)(nil), // 1: workflow.v1.WorkflowServiceHealthzResponse
	(*WorkflowServiceReadyzRequest)(nil),   // 2: workflow.v1.WorkflowServiceReadyzRequest
	(*WorkflowServiceReadyzResponse)(nil),  // 3: workflow.v1.WorkflowServiceReadyzResponse
	(*CreateExecutionRequest)(nil),         // 4: workflow.v1.CreateExecutionRequest
	(*CreateExecutionResponse)(nil),        // 5: workflow.v1.CreateExecutionResponse
	(*CreateExecutionData)(nil),            // 6: workflow.v1.CreateExecutionData
	(*GetExecutionRequest)(nil),            // 7: workflow.v1.GetExecutionRequest
	(*GetExecutionResponse)(nil),           // 8: workflow.v1.GetExecutionResponse
	(*ListExecutionsRequest)(nil),          // 9: workflow.v1.ListExecutionsRequest
	(*ListExecutionsResponse)(nil),         // 10: workflow.v1.ListExecutionsResponse
	(*ExecutionPage)(nil),                  // 11: workflow.v1.ExecutionPage
	(*Execution)(nil),                      // 12: workflow.v1.Execution
	(*ListNodeTypesRequest)(nil),           // 13: workflow.v1.ListNodeTypesRequest
	(*ListNodeTypesResponse)(nil),          // 14: workflow.v1.ListNodeTypesResponse
	(*NodeType)(nil),                       // 15: workflow.v1.NodeType
	(*InputDefinition)(nil),                // 16: workflow.v1.InputDefinition
	(*OutputDefinition)(nil),               // 17: workflow.v1.OutputDefinition
	(*CreateWorkflowRequest)(nil),          // 18: workflow.v1.CreateWorkflowRequest
	(*CreateWorkflowResponse)(nil),         // 19: workflow.v1.CreateWorkflowResponse
	(*ListWorkflowsRequest)(nil),           // 20: workflow.v1.ListWorkflowsRequest
	(*ListWorkflowsResponse)(nil),          // 21: workflow.v1.ListWorkflowsResponse
	(*WorkflowPage)(nil),                   // 22: workflow.v1.WorkflowPage
	(*GetWorkflowRequest)(nil),             // 23: workflow.v1.GetWorkflowRequest
	(*GetWorkflowResponse)(nil),            // 24: workflow.v1.GetWorkflowResponse
	(*Workflow)(nil),                       // 25: workflow.v1.Workflow
	(*Definition)(nil),                     // 26: workflow.v1.Definition
	(*Node)(nil),                           // 27: workflow.v1.Node
	(*Edge)(nil),                           // 28: workflow.v1.Edge
	nil,                                    // 29: workflow.v1.NodeType.InputsEntry
	nil,                                    // 30: workflow.v1.NodeType.OutputsEntry
	nil,                                    // 31: workflow.v1.Node.PresetEntry
	(*structpb.Struct)(nil),                // 32: google.protobuf.Struct
	(*structpb.Value)(nil),                 // 33: google.protobuf.Value
	(*timestamppb.Timestamp)(nil),          // 34: google.protobuf.Timestamp
}
var file_workflow_v1_workflow_proto_depIdxs = []int32{
	32, // 0: workflow.v1.CreateExecutionRequest.input:type_name -> google.protobuf.Struct
	6,  // 1: workflow.v1.CreateExecutionResponse.data:type_name -> workflow.v1.CreateExecutionData
	12, // 2: workflow.v1.GetExecutionResponse.data:type_name -> workflow.v1.Execution
	11, // 3: workflow.v1.ListExecutionsResponse.data:type_name -> workflow.v1.ExecutionPage
	12, // 4: workflow.v1.ExecutionPage.executions:type_name -> workflow.v1.Execution
	32, // 5: workflow.v1.Execution.input:type_name -> google.protobuf.Struct
	33, // 6: workflow.v1.Execution.output:type_name -> google.protobuf.Value
	34, // 7: workflow.v1.Execution.created_at:type_name -> google.protobuf.Timestamp
	34, // 8: workflow.v1.Execution.started_at:type_name -> google.protobuf.Timestamp
	34, // 9: workflow.v1.Execution.completed_at:type_name -> google.protobuf.Timestamp
	34, // 10: workflow.v1.Execution.updated_at:type_name -> google.protobuf.Timestamp
	15, // 11: workflow.v1.ListNodeTypesResponse.node_types:type_name -> workflow.v1.NodeType
	29, // 12: workflow.v1.NodeType.inputs:type_name -> workflow.v1.NodeType.InputsEntry
	30, // 13: workflow.v1.NodeType.outputs:type_name -> workflow.v1.NodeType.OutputsEntry
	26, // 14: workflow.v1.CreateWorkflowRequest.definition:type_name -> workflow.v1.Definition
	25, // 15: workflow.v1.CreateWorkflowResponse.data:type_name -> workflow.v1.Workflow
	22, // 16: workflow.v1.ListWorkflowsResponse.data:type_name -> workflow.v1.WorkflowPage
	25, // 17: workflow.v1.WorkflowPage.workflows:type_name -> workflow.v1.Workflow
	25, // 18: workflow.v1.GetWorkflowResponse.data:type_name -> workflow.v1.Workflow
	26, // 19: workflow.v1.Workflow.definition:type_name -> workflow.v1.Definition
	34, // 20: workflow.v1.Workflow.created_at:type_name -> google.protobuf.Timestamp
	34, // 21: workflow.v1.Workflow.updated_at:type_name -> google.protobuf.Timestamp
	27, // 22: workflow.v1.Definition.nodes:type_name -> workflow.v1.Node
	28, // 23: workflow.v1.Definition.edges:type_name -> workflow.v1.Edge
	31, // 24: workflow.v1.Node.preset:type_name -> workflow.v1.Node.PresetEntry
	16, // 25: workflow.v1.NodeType.InputsEntry.value:type_name -> workflow.v1.InputDefinition
	17, // 26: workflow.v1.NodeType.OutputsEntry.value:type_name -> workflow.v1.OutputDefinition
	33, // 27: workflow.v1.Node.PresetEntry.value:type_name -> google.protobuf.Value
	0,  // 28: workflow.v1.WorkflowService.Healthz:input_type -> workflow.v1.WorkflowServiceHealthzRequest
	2,  // 29: workflow.v1.WorkflowService.Readyz:input_type -> workflow.v1.WorkflowServiceReadyzRequest
	4,  // 30: workflow.v1.WorkflowService.CreateExecution:input_type -> workflow.v1.CreateExecutionRequest
	7,  // 31: workflow.v1.WorkflowService.GetExecution:input_type -> workflow.v1.GetExecutionRequest
	9,  // 32: workflow.v1.WorkflowService.ListExecutions:input_type -> workflow.v1.ListExecutionsRequest
	13, // 33: workflow.v1.WorkflowService.ListNodeTypes:input_type -> workflow.v1.ListNodeTypesRequest
	18, // 34: workflow.v1.WorkflowService.CreateWorkflow:input_type -> workflow.v1.CreateWorkflowRequest
	20, // 35: workflow.v1.WorkflowService.ListWorkflows:input_type -> workflow.v1.ListWorkflowsRequest
	23, // 36: workflow.v1.WorkflowService.GetWorkflow:input_type -> workflow.v1.GetWorkflowRequest
	1,  // 37: workflow.v1.WorkflowService.Healthz:output_type -> workflow.v1.WorkflowServiceHealthzResponse
	3,  // 38: workflow.v1.WorkflowService.Readyz:output_type -> workflow.v1.WorkflowServiceReadyzResponse
	5,  // 39: workflow.v1.WorkflowService.CreateExecution:output_type -> workflow.v1.CreateExecutionResponse
	8,  // 40: workflow.v1.WorkflowService.GetExecution:output_type -> workflow.v1.GetExecutionResponse
	10, // 41: workflow.v1.WorkflowService.ListExecutions:output_type -> workflow.v1.ListExecutionsResponse
	14, // 42: workflow.v1.WorkflowService.ListNodeTypes:output_type -> workflow.v1.ListNodeTypesResponse
	19, // 43: workflow.v1.WorkflowService.CreateWorkflow:output_type -> workflow.v1.CreateWorkflowResponse
	21, // 44: workflow.v1.WorkflowService.ListWorkflows:output_type -> workflow.v1.ListWorkflowsResponse
	24, // 45: workflow.v1.WorkflowService.GetWorkflow:output_type -> workflow.v1.GetWorkflowResponse
	37, // [37:46] is the sub-list for method output_type
	28, // [28:37] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_workflow_v1_workflow_proto_init() }
func file_workflow_v1_workflow_proto_init() {
	if File_workflow_v1_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_v1_workflow_proto_rawDesc), len(file_workflow_v1_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflow_v1_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_v1_workflow_proto_depIdxs,
		MessageInfos:      file_workflow_v1_workflow_proto_msgTypes,
	}.Build()
	File_workflow_v1_workflow_proto = out.File
	file_workflow_v1_workflow_proto_goTypes = nil
	file_workflow_v1_workflow_proto_depIdxs = nil
}
