// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: worker/v1/worker.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	mi := &file_worker_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

type HealthzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_worker_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{1}
}

type ReadyzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyzRequest) Reset() {
	*x = ReadyzRequest{}
	mi := &file_worker_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyzRequest) ProtoMessage() {}

func (x *ReadyzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyzRequest.ProtoReflect.Descriptor instead.
func (*ReadyzRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{2}
}

type ReadyzResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyzResponse) Reset() {
	*x = ReadyzResponse{}
	mi := &file_worker_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyzResponse) ProtoMessage() {}

func (x *ReadyzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyzResponse.ProtoReflect.Descriptor instead.
func (*ReadyzResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_worker_proto_rawDescGZIP(), []int{3}
}

var File_worker_v1_worker_proto protoreflect.FileDescriptor

const file_worker_v1_worker_proto_rawDesc = "" +
	"\n" +
	"\x16worker/v1/worker.proto\x12\tworker.v1\x1a\x1cgoogle/api/annotations.proto\"\x10\n" +
	"\x0eHealthzRequest\"\x11\n" +
	"\x0fHealthzResponse\"\x0f\n" +
	"\rReadyzRequest\"\x10\n" +
	"\x0eReadyzResponse2\xaf\x01\n" +
	"\rWorkerService\x12O\n" +
	"\aHealthz\x12\x19.worker.v1.HealthzRequest\x1a\x1a.worker.v1.HealthzResponse\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/live\x12M\n" +
	"\x06Readyz\x12\x18.worker.v1.ReadyzRequest\x1a\x19.worker.v1.ReadyzResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/readyBGZEgit.sotatts.online/matrix/matrix/workflow/api-server/api/worker/v1;v1b\x06proto3"

var (
	file_worker_v1_worker_proto_rawDescOnce sync.Once
	file_worker_v1_worker_proto_rawDescData []byte
)

func file_worker_v1_worker_proto_rawDescGZIP() []byte {
	file_worker_v1_worker_proto_rawDescOnce.Do(func() {
		file_worker_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_v1_worker_proto_rawDesc), len(file_worker_v1_worker_proto_rawDesc)))
	})
	return file_worker_v1_worker_proto_rawDescData
}

var file_worker_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_worker_v1_worker_proto_goTypes = []any{
	(*HealthzRequest)(nil),  // 0: worker.v1.HealthzRequest
	(*HealthzResponse)(nil), // 1: worker.v1.HealthzResponse
	(*ReadyzRequest)(nil),   // 2: worker.v1.ReadyzRequest
	(*ReadyzResponse)(nil),  // 3: worker.v1.ReadyzResponse
}
var file_worker_v1_worker_proto_depIdxs = []int32{
	0, // 0: worker.v1.WorkerService.Healthz:input_type -> worker.v1.HealthzRequest
	2, // 1: worker.v1.WorkerService.Readyz:input_type -> worker.v1.ReadyzRequest
	1, // 2: worker.v1.WorkerService.Healthz:output_type -> worker.v1.HealthzResponse
	3, // 3: worker.v1.WorkerService.Readyz:output_type -> worker.v1.ReadyzResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_worker_v1_worker_proto_init() }
func file_worker_v1_worker_proto_init() {
	if File_worker_v1_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_v1_worker_proto_rawDesc), len(file_worker_v1_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_v1_worker_proto_goTypes,
		DependencyIndexes: file_worker_v1_worker_proto_depIdxs,
		MessageInfos:      file_worker_v1_worker_proto_msgTypes,
	}.Build()
	File_worker_v1_worker_proto = out.File
	file_worker_v1_worker_proto_goTypes = nil
	file_worker_v1_worker_proto_depIdxs = nil
}
