// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: worker/v1/worker.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationWorkerServiceHealthz = "/worker.v1.WorkerService/Healthz"
const OperationWorkerServiceReadyz = "/worker.v1.WorkerService/Readyz"

type WorkerServiceHTTPServer interface {
	// Healthz Healthz 检查 Worker 进程是否存活。
	Healthz(context.Context, *HealthzRequest) (*HealthzResponse, error)
	// Readyz Readyz 检查 Worker 是否可以接收任务。
	Readyz(context.Context, *ReadyzRequest) (*ReadyzResponse, error)
}

func RegisterWorkerServiceHTTPServer(s *http.Server, srv WorkerServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/live", _WorkerService_Healthz0_HTTP_Handler(srv))
	r.Handle("GET", "/ready", _WorkerService_Readyz0_HTTP_Handler(srv))
}

func _WorkerService_Healthz0_HTTP_Handler(srv WorkerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HealthzRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkerServiceHealthz)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Healthz(ctx, req.(*HealthzRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HealthzResponse)
		return ctx.Result(200, reply)
	}
}

func _WorkerService_Readyz0_HTTP_Handler(srv WorkerServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReadyzRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationWorkerServiceReadyz)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Readyz(ctx, req.(*ReadyzRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReadyzResponse)
		return ctx.Result(200, reply)
	}
}

type WorkerServiceHTTPClient interface {
	// Healthz Healthz 检查 Worker 进程是否存活。
	Healthz(ctx context.Context, req *HealthzRequest, opts ...http.CallOption) (rsp *HealthzResponse, err error)
	// Readyz Readyz 检查 Worker 是否可以接收任务。
	Readyz(ctx context.Context, req *ReadyzRequest, opts ...http.CallOption) (rsp *ReadyzResponse, err error)
}

type WorkerServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewWorkerServiceHTTPClient(client *http.Client) WorkerServiceHTTPClient {
	return &WorkerServiceHTTPClientImpl{client}
}

// Healthz Healthz 检查 Worker 进程是否存活。
func (c *WorkerServiceHTTPClientImpl) Healthz(ctx context.Context, in *HealthzRequest, opts ...http.CallOption) (*HealthzResponse, error) {
	var out HealthzResponse
	pattern := "/live"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationWorkerServiceHealthz),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Readyz Readyz 检查 Worker 是否可以接收任务。
func (c *WorkerServiceHTTPClientImpl) Readyz(ctx context.Context, in *ReadyzRequest, opts ...http.CallOption) (*ReadyzResponse, error) {
	var out ReadyzResponse
	pattern := "/ready"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationWorkerServiceReadyz),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
